### ISSUE TITLE
cyclic reference from ImmutabilityChecker to itself (through ctor)

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi#173]
```
log4j:ERROR Could not instantiate class [com.jcabi.log.MulticolorLayout].
org.aspectj.lang.NoAspectBoundException: com.jcabi.aspects.aj.ImmutabilityChecker
    at com.jcabi.aspects.aj.ImmutabilityChecker.aspectOf(ImmutabilityChecker.java:1)
    at com.jcabi.log.MulticolorLayout.<init>(MulticolorLayout.java:88)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at java.lang.Class.newInstance0(Class.java:372)
    at java.lang.Class.newInstance(Class.java:325)
    at org.apache.log4j.helpers.OptionConverter.instantiateByClassName(OptionConverter.java:337)
    at org.apache.log4j.helpers.OptionConverter.instantiateByKey(OptionConverter.java:124)
    at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:797)
    at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
    at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
    at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
    at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
    at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
    at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
    at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:64)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:270)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
    at com.jcabi.log.Logger.logger(Logger.java:288)
    at com.jcabi.log.Logger.isInfoEnabled(Logger.java:264)
    at com.jcabi.log.Logger.info(Logger.java:185)
    at com.jcabi.aspects.aj.ImmutabilityChecker.<init>(ImmutabilityChecker.java:63)
    at com.jcabi.aspects.aj.ImmutabilityChecker.ajc$postClinit(ImmutabilityChecker.java:1)
    at com.jcabi.aspects.aj.ImmutabilityChecker.<clinit>(ImmutabilityChecker.java:1)
    at com.rexsl.core.ProductVersion.<init>(ProductVersion.java:67)
```

**Comment by lucasdaniele1** [comment]
Hi, Could you tell me how do you fix it. Thanks
