### ISSUE TITLE
feature to disable JSR-303 validation?

### ISSUE THREAD

**Issue by cobbzilla** [jcabi/jcabi#316]
I would like to use jcabi for annotations like @RetryOnFailure, @Async and @Cacheable, but whenever I run my tests I get the following error:

    java.lang.NoSuchMethodError: javax.validation.Validator.forExecutables()Ljavax/validation/executable/ExecutableValidator;

The project I'm working on has an existing Jersey/JAX-RS project that already has validation configured (@Valid tags on method parameters are handled by the framework), using a customized/subclassed version of the Hibernate validator.

Is there any way to disable JSR-303 validation via jcabi, if it is already being provided by someone else?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@cobbzilla good question... Can you provide full stack trace please?

**Comment by cobbzilla** [comment]
I've pasted a stack trace below. The signature for `mypackage.AuthResource.login` includes a parameter that is annotated with `@Valid`. My Jersey/JAX-RS container is already handling validation for this. It seems that when the jcabi aspects were woven-in at compile time, it added some code here that is messing up validation. Would it be possible to disable certain annotations in the maven plugin that handles the aspect-weaving stuff? That would be super helpful.


`Feb 01, 2017 6:18:04 PM com.sun.jersey.spi.container.ContainerResponse mapMappableContainerException
SEVERE: The exception contained within MappableContainerException could not be mapped to a response, re-throwing to the HTTP container
java.lang.AbstractMethodError: org.hibernate.validator.internal.engine.ValidatorImpl.forExecutables()Ljavax/validation/executable/ExecutableValidator;
	at com.jcabi.aspects.aj.MethodValidator.validateMethod(MethodValidator.java:155)
	at com.jcabi.aspects.aj.MethodValidator.beforeMethod(MethodValidator.java:87)
	at mypackage.AuthResource.login(AuthResource.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.server.impl.container.grizzly2.GrizzlyContainer._service(GrizzlyContainer.java:222)
	at com.sun.jersey.server.impl.container.grizzly2.GrizzlyContainer.service(GrizzlyContainer.java:192)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:744)`

**Comment by cobbzilla** [comment]
@yegor256 just pinging, would love to use your library but am still stuck here.

**Comment by yegor256** [comment]
@cobbzilla it seems that you have two validating engines in the classpath. You should exclude Hibernate and try again. Most probably it's coming together with one of jcabi dependencies, but I'm not sure. Check the list of your deps and exclude it.
