### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.jcabi.manifests.Manifests

### ISSUE THREAD

**Issue by Penglong-LE** [jcabi/jcabi#333]
Make sure the title of the issue explains the problem you are having. Also, the description of the issue must clearly explain what is broken, not what you want us to implement. Go through this checklist and make sure you answer "YES" to all points:

  - You have all pre-requisites listed in README.md installed
  - You are sure that you are not reporting a duplicate (search all issues)
  - You say "is broken" or "doesn't work" in the title
  - You tell us what you are trying to do
  - You explain the results you are getting
  - You suggest an alternative result you would like to see

This article will help you understand what we are looking for: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

Thank you for your contribution!

in our project, when calling Manifests.read method, it always throws an exception NoClassDefFoundError, seems the root cause is the initialization of static block failed in Manifests as the message shown below, I don't know why this error happen, and how to fix, could someone help ?

Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at com.jcabi.log.PreFormatter.process(PreFormatter.java:122) ~[jcabi-log-0.14.jar:?]
        at com.jcabi.log.PreFormatter.<init>(PreFormatter.java:77) ~[jcabi-log-0.14.jar:?]
        at com.jcabi.log.Logger.format(Logger.java:116) ~[jcabi-log-0.14.jar:?]
        at com.jcabi.log.Logger.error(Logger.java:240) ~[jcabi-log-0.14.jar:?]
        at com.jcabi.manifests.Manifests.<clinit>(Manifests.java:140) ~[jcabi-manifests-1.1.jar:?]

**Comment by janenicholson** [comment]
This was enough information for me to determine that com.jcabi.manifests.Manifests has a bug here

    static {
        try {
            Manifests.DEFAULT.append(new ClasspathMfs());
        } catch (final IOException ex) {
            Logger.error(
                Manifests.class,
                "#load(): '%s' failed %[exception]s", ex
            );
        }
    }

The error message has 2 %s but only one arg to fill it, and is therefore ArrayOutOfBounds-ing
